version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - './sql-data/db:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: 'proyecto_lab'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
       - "3306:3306"